/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Widi Ramadhan
 */
public class menuutama extends javax.swing.JFrame {
    koneksi kon=new koneksi();

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        initComponents();
        kon.setKoneksi();
        setResizable(false);
        ceklogin();
    }
    
    private void ceklogin(){
        try{
            String sql="select * from pengguna where status='active'";
            kon.rs=kon.st.executeQuery(sql);
            if (kon.rs.next()){
                String nama=kon.rs.getString("nama");
                String akseslevel=kon.rs.getString("hak_akses");
                lnama.setText(nama);
                lhak.setText(akseslevel);
                String hak=lhak.getText();
                    if(hak.equals("user")){
                        mnFile.setEnabled(false);
                    }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void logout(){
        try{
                 String status="update pengguna set status='non-active' where nama='"+lnama.getText()+"'";
                 kon.st.executeUpdate(status);
                 
                }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
                    
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lhak = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnPengguna = new javax.swing.JMenuItem();
        mnKaryawan = new javax.swing.JMenuItem();
        mnJabatan = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnLaporan = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenu();
        mnBackupRestore = new javax.swing.JMenuItem();
        mnTentang = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenu();
        mnlogout = new javax.swing.JMenuItem();
        mnclose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penggajian CV. Amanah Reka Tekno Inti ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuutama.jpg"))); // NOI18N

        jLabel3.setText("Selamat Datang, ");

        lnama.setText("lnama");

        jLabel2.setText("Hak akses anda");

        lhak.setText("lhak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(lhak)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lnama)
                    .addComponent(jLabel2)
                    .addComponent(lhak)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar2.setPreferredSize(new java.awt.Dimension(259, 70));

        mnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file.png"))); // NOI18N
        mnFile.setText(" File");
        mnFile.setActionCommand("File");
        mnFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnFile.setMaximumSize(new java.awt.Dimension(45, 32767));
        mnFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengguna.png"))); // NOI18N
        mnPengguna.setText("Data Pengguna");
        mnPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPenggunaActionPerformed(evt);
            }
        });
        mnFile.add(mnPengguna);

        mnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/karyawan.png"))); // NOI18N
        mnKaryawan.setText("Data Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        mnFile.add(mnKaryawan);

        mnJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabatan.png"))); // NOI18N
        mnJabatan.setText("Data Jabatan");
        mnJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJabatanActionPerformed(evt);
            }
        });
        mnFile.add(mnJabatan);

        mnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tunjangan.png"))); // NOI18N
        mnMaster.setText("Data Master");
        mnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMasterActionPerformed(evt);
            }
        });
        mnFile.add(mnMaster);

        jMenuBar2.add(mnFile);

        mnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi.png"))); // NOI18N
        mnTransaksi.setText("Transaksi");
        mnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnTransaksiMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnTransaksi);

        mnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        mnLaporan.setText("Laporan");
        mnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnLaporanMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnLaporan);

        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengaturan.png"))); // NOI18N
        mnAbout.setText("Pengaturan");
        mnAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnAbout.setVerifyInputWhenFocusTarget(false);
        mnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnBackupRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simpan.png"))); // NOI18N
        mnBackupRestore.setText("Cadangkan & Pulihkan Data");
        mnBackupRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBackupRestoreActionPerformed(evt);
            }
        });
        mnAbout.add(mnBackupRestore);

        mnTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        mnTentang.setText("Tentang Aplikasi");
        mnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTentangActionPerformed(evt);
            }
        });
        mnAbout.add(mnTentang);

        jMenuBar2.add(mnAbout);

        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signout.png"))); // NOI18N
        mnExit.setText("Keluar");
        mnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        mnlogout.setText("Keluar dari akun");
        mnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnlogoutActionPerformed(evt);
            }
        });
        mnExit.add(mnlogout);

        mnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        mnclose.setText("Tutup Program");
        mnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncloseActionPerformed(evt);
            }
        });
        mnExit.add(mnclose);

        jMenuBar2.add(mnExit);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(817, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mncloseActionPerformed

    private void mnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlogoutActionPerformed
        // TODO add your handling code here:
        logout();
        login fl = new login();
        fl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnlogoutActionPerformed

    private void mnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPenggunaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        user pengguna=new user();
        pengguna.setVisible(true);
    }//GEN-LAST:event_mnPenggunaActionPerformed

    private void mnJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJabatanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        jabatan jab=new jabatan();
        jab.setVisible(true);
    }//GEN-LAST:event_mnJabatanActionPerformed

    private void mnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTentangActionPerformed
        // TODO add your handling code here:
        this.dispose();
        tentang about=new tentang();
        about.setVisible(true);
    }//GEN-LAST:event_mnTentangActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        // TODO add your handling code here:
        karyawan kar=new karyawan();
        kar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMasterActionPerformed
        // TODO add your handling code here:
        master m=new master();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnMasterActionPerformed

    private void mnBackupRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBackupRestoreActionPerformed
        // TODO add your handling code here:
        backuprestore br=new backuprestore();
        br.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnBackupRestoreActionPerformed

    private void mnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnLaporanMouseClicked
        // TODO add your handling code here:
        laporan lap=new laporan();
        lap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnLaporanMouseClicked

    private void mnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTransaksiMouseClicked
        // TODO add your handling code here:
        transaksi trans=new transaksi();
        trans.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lhak;
    private javax.swing.JLabel lnama;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenuItem mnBackupRestore;
    private javax.swing.JMenu mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnJabatan;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnMaster;
    private javax.swing.JMenuItem mnPengguna;
    private javax.swing.JMenuItem mnTentang;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenuItem mnclose;
    private javax.swing.JMenuItem mnlogout;
    // End of variables declaration//GEN-END:variables
}
